server:
  port: 7001

spring:
  security:
    user:
      name: www
      password: www362412

eureka:
  instance:
    hostname: localhost #服务注册中心实例的主机名
  client:
    fetch-registry: false #此客户端是否获取eureka服务器注册表上的注册信息，默认为true
    register-with-eureka: false  #实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true
    service-url:
      #与Eureka注册服务中心的通信zone和url地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
