########################
# springboot核心配置文件
# application.properties、application.yml、application.yaml三选一
# 优先级：application.properties>application.yml=application.yaml
########################
server:
  port: 8080
  servlet:
    #访问路径设置
    context-path: /
#spring配置
spring:
  #设置tomcat端口号
  profiles:
    #配置环境文件
    active: dev
  #thymelea模板配置
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    #热部署文件，页面不产生缓存，及时更新
    cache: false
  #数据库配置
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: jdbc:oracle:thin:@192.168.19.128:1521:xe
    username: boot
    password: www362412
  #redis配置
  redis:
    host: 192.168.19.128
    port: 6379
    password:
#Mybatis配置
#mapper.xml在resource文件夹下的配置
mybatis:
  mapper-locations: classpath:mapper/*.xml

#配置JSP视图解析器
#spring.mvc.view.prefix=/
#spring.mvc.view.suffix=.jsp

#日志设置
#logging.file=D:/log/log.log
#logging.level.org.org.springframework.web=info


#https的SSL配置
#server.ssl.key-store=./StudyDemo/tomcat.keystore
#server.ssl.key-store-password=www362412
#server.ssl.key-store-type=JKS
#server.ssl.key-alias=tomcat

#图标设置,默认为true
#spring.mvc.favicon.enabled=true

##设置控制器输出的json字符串更美观
#spring.jackson.serialization.indent-output=true

#JPA配置
#提供根据实体类自动维护数据库表结构的功能，如：update、create、create-drop、validate、none
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true

#缓存配置
#缓存类型，有：generic、ehcache、hazelcast、infinispan、jcache、redis、guava、simple、none
#spring.cache.type=ehcache

#“---”可分开配置多环境文件，等效application-test.yaml
---
spring:
  profiles: test
server:
  port: 8082
