########################
# springboot核心配置文件
# application.properties、application.yml、application.yaml三选一
# 优先级：application.properties>application.yml=application.yaml
########################
#服务器配置
server:
  port: 8080
  servlet:
    #访问路径设置
    context-path: /
#日志设置
logging:
  file:
    path: D:/log/BootDemo
  level:
    com.www.demo.model.mapper: debug
#spring配置
spring:
  #security配置用户
#  security:
#    user:
#      name: www
#      password: www362412
#      roles: admin
  messages:
    # i18n国际化文件路径
    basename: i18n.login
  #设置tomcat端口号
  profiles:
    #配置环境文件
    active: dev
  #thymelea模板配置
  thymeleaf:
    #热部署文件，页面不产生缓存，及时更新
    cache: false
    suffix: .html
    mode: HTML5
  #数据库配置
  datasource:
    #使用druid数据源，以下5个参数可省略
#    driver-class-name: oracle.jdbc.OracleDriver
#    url: jdbc:oracle:thin:@192.168.19.128:1521:xe
#    username: boot
#    password: www362412
#    type: com.alibaba.druid.pool.DruidDataSource
    #druid配置
    druid:
      db-type: oracle #数据库类型
      url: jdbc:oracle:thin:@192.168.19.128:1521:xe
      username: boot
      password: www362412
      initial-size: 5 #启动程序时，在连接池中初始化多少个连接
      min-idle: 5 #最小连接池数量
      max-active: 20 #连接池中最多支持多少个活动会话
      max-wait: 60000 #程序向连接池中请求连接时,超过maxWait的值后，认为本次请求失败，即连接池
      #有两个含义： 1) Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。 2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
      time-between-eviction-runs-millis: 6000
      min-evictable-idle-time-millis: 300000 #连接保持空闲而不被驱逐的最小时间
      #用来检测连接是否有效的sql，要求是一个查询语句，常用select 'x'。如果validationQuery为null，testOnBorrow、testOnReturn、testWhileIdle都不会起作用。
      validation-query: SELECT 1 FROM DUAL
      test-on-borrow: false #申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false #归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      pool-prepared-statements: true #是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      filters: stat,wall,log4j #属性类型是字符串，通过别名的方式配置扩展插件，常用的插件有： 监控统计用的filter:stat 日志用的filter:log4j 防御sql注入的filter:wall
      #要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。在Druid中，不会存在Oracle下PSCache占用内存过多的问题，可以把这个数值配置大一些，比如说100
      max-pool-prepared-statement-per-connection-size: 20
      use-global-data-source-stat: true #
      connect-properties: druid.stat.mergeSql=true,druid.stat.slowSqlMillis=500 #
  #redis配置
  redis:
    host: 192.168.19.128
    port: 6379
    password: www362412
#Mybatis配置
#mapper.xml在resource文件夹下的配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  #实现数据库下划线字段到POJO类驼峰形式的自动映射
  configuration:
    map-underscore-to-camel-case: true

#配置JSP视图解析器
#spring.mvc.view.prefix=/
#spring.mvc.view.suffix=.jsp

#https的SSL配置
#server.ssl.key-store=./StudyDemo/tomcat.keystore
#server.ssl.key-store-password=www362412
#server.ssl.key-store-type=JKS
#server.ssl.key-alias=tomcat

#图标设置,默认为true
#spring.mvc.favicon.enabled=true

##设置控制器输出的json字符串更美观
#spring.jackson.serialization.indent-output=true

#JPA配置
#提供根据实体类自动维护数据库表结构的功能，如：update、create、create-drop、validate、none
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true

#缓存配置
#缓存类型，有：generic、ehcache、hazelcast、infinispan、jcache、redis、guava、simple、none
#spring.cache.type=ehcache

#“---”可分开配置多环境文件，等效application-test.yaml

---
spring:
  profiles: test
server:
  port: 8082
