server:
  port: 8080
  servlet:
    context-path: /
#spring配置
spring:
  application:
    name: cloud-provider
#eureka配置
eureka:
  client:
    service-url:
      defaultZone : http://www:www362412@localhost:7001/eureka/ #注册中心地址
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port} #该实例注册到服务中心的唯一ID
    prefer-ip-address: true #该实例，相较于hostname是否优先使用IP
#配置eureka注册中心服务的status信息
info:
  name: spring cloud provider test

