server:
  port: 3344

spring:
  application:
    name: spring-cloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wenzdaywww/spring-cloud-config
          # github的默认分支已由master改为main，所以这边需要设置默认分支
          default-label: main