server:
  port: 8070
  servlet:
    context-path: /
#spring配置
spring:
  application:
    name: cloud-consumer
#eureka配置
eureka:
  client:
    fetch-registry: true #此客户端是否获取eureka服务器注册表上的注册信息，默认为true
    register-with-eureka: false  #实例是否在eureka服务器上注册自己的信息以供其他服务发现，默认为true
    service-url:
      #配置eureka集群地址
      defaultZone : http://www:www362412@localhost:7002/eureka/,http://www:www362412@localhost:7003/eureka/,http://www:www362412@localhost:7004/eureka/ #注册中心地址
  instance:
    instance-id: ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port} #该实例注册到服务中心的唯一ID
    prefer-ip-address: true #该实例，相较于hostname是否优先使用IP
#ribbon配置
ribbon:
  eureka:
    enabled: true
